name: Dummy Rest API Automation

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

  schedule:
    - cron: '0 2 * * *'

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pyhton
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.10'

      - name: Install Dependecies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright
        run: |
          playwright install --with-deps
        
      - name: Run Playwright API Tests
        run: |
          pytest -v

      - # Upload test reports
      - name: Upload pytest report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: |
            reports/
            test-results/

